# Dockerfile.nginx: ShunyaLink Load Balancer Image 🐳⚖️

FROM nginx:1.25.3-alpine

# Use custom config for HA Load Balancing
COPY nginx.conf /etc/nginx/nginx.conf

# Expose HTTP
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
